### ISSUE TITLE
A plan for asynchronous driver

### ISSUE THREAD

**Issue by ediskandarov-cur** [chanzuckerberg/aurora-data-api#26]
Hi there,

SQLAlchemy 1.4 is releasing soon. Along with new features, it offers an async extension, which yields a perfect combination for async web frameworks.

I wonder if there a plan for making `aurora-data-api` asynchronous?

That's a difficult problem since there's no async support from the official boto3 and botocore libraries.

On the other hand, there are [aiobotocore](https://github.com/aio-libs/aiobotocore) and [aioboto3](https://github.com/terrycain/aioboto3) from the community.

## Proposal

Perhaps, downgrading boto3 to botocore in this lib would be a good first step.

The next one would be adding an async version of the driver, so that there are 2 drivers:

1. sync driver based on `botocore`
2. async driver based on `aiobotocore`(the dependency shall be available in extra requirements)

What do you think? @kislyuk

**Comment by kislyuk** [comment]
Hello, thank you for your interest in aurora-data-api. Async support is not high on my priority list right now. Changing from boto3 to botocore is possible, since we are not using any boto3-specific functionality. The biggest issue is that I don't routinely use async code and would probably not feel comfortable maintaining async code, and I'm not clear on what kind of strategy would be needed to avoid duplicating code. If someone is interested in committing and supporting an async implementation that doesn't disrupt the existing codebase or duplicate code, I am open to merging it.

**Comment by kislyuk** [comment]
No plans to implement this. If this library were to implement this, AWS would have to support asyncio in boto3 or another official SDK first.
